---
- hosts: ocp
  name: Release system

  tasks:
    - name: Unsubscribe system
      shell: subscription-manager remove --all

- hosts: osp
  name: Delete OpenShift Cluster

  tasks:
    - name: Delete servers
      shell: >
            source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
            openstack server delete {{ item }} --wait
      with_items: "{{ groups['ocp'] }}"

    - name: Delete ports
      shell: >
            source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
            openstack port delete {{ item }}-port
      with_items: "{{ groups['ocp'] }}"

    - name: Delete docker storage volumes
      shell: >
            source ~/keystonerc_admin && export OS_PROJECT_NAME=lab && \
            openstack volume delete {{ hostvars[item]["docker_storage"]["volume"] }}
      with_items: "{{ groups['ocp'] }}"
